= 커뮤니티 API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

:operation-http-request-title: HTTP 요청 예시
:operation-request-headers-title: 요청 헤더
:operation-request-fields-title: 요청 필드
:operation-path-parameters-title: 경로 변수

:operation-http-response-title: HTTP 응답 예시
:operation-response-fields-title: 응답 필드

[[인증-API]]
== 인증
=== 로그인
operation::login/로그인[snippets='http-request,request-fields,http-response,response-fields']

[[회원-API]]
== 회원
=== 회원가입
operation::members/회원가입[snippets='http-request,request-fields,http-response']

=== 회원정보
operation::members/회원정보_조회[snippets='http-request,path-parameters,http-response,response-fields']

=== 회원 상세정보
operation::members/회원_상세정보_조회[snippets='http-request,request-headers,http-response,response-fields']

[[카테고리-API]]
== 카테고리
=== 등록
operation::category/카테고리등록[snippets='http-request,request-fields,http-response']

=== 조회
operation::category/카테고리조회[snippets='http-request,path-parameters,http-response']

=== 수정
operation::category/카테고리수정[snippets='http-request,path-parameters,request-fields,http-response']

=== 삭제
operation::category/카테고리삭제[snippets='http-request,path-parameters,http-response']

[[게시글-API]]
== 게시글
=== 등록
operation::post/게시글등록[snippets='http-request,request-fields,http-response']

=== 조회
operation::post/게시글조회[snippets='http-request,path-parameters,http-response']

=== 수정
operation::post/게시글수정[snippets='http-request,path-parameters,request-fields,http-response']

=== 삭제
operation::post/게시글삭제[snippets='http-request,path-parameters,http-response']

[[답글API]]
== 답글
=== 추가
operation::reply/게시글에_답글추가[snippets='http-request,path-parameters,request-fields,http-response']

=== 조회
operation::reply/게시글의_답글목록_조회[snippets='http-request,path-parameters,http-response,response-fields']

=== 수정
operation::reply/답글수정[snippets='http-request,path-parameters,request-fields,http-response']

=== 삭제
operation::reply/답글삭제[snippets='http-request,path-parameters,http-response']