version: "3.9"
services:
  mysql:
    container_name: sm-mysql
    image: "mysql:8.0.30"
    ports:
      - "13306:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--innodb_ft_min_token_size=2"
    volumes:
      - "sm-mysql-vol:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test

volumes:
  sm-mysql-vol: