spring:
  profiles:
    group:
      dev:
        - dev-auth
        - dev-db
        - dev-env
        - prod-mail
        - prod-oauth2
    active: dev
  messages:
    basename: messages,errors

management:
  server:
    port: 7070
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: /smc-mgnt
      exposure:
        include:
          - info
          - health
  endpoint:
    info.enabled: true
    health.enabled: true