spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    url: jdbc:mysql://localhost:13306/test?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: test
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: 'create-drop'
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      platform: dev

server:
  port: 8443
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: temp-ssl

logging:
  config: classpath:log4j2-spring-console.xml

decorator:
  datasource:
    p6spy:
      enable-logging: true

dummy-store:
  root: "C:/Small-Community"
  attachments: ${dummy-store.root}/attachments

jwt:
  secret-key: 'DUMMY'

oauth2:
  authorizedDomains: https://localhost:3000,https://cijtoy.com