spring:
  config:
    activate:
      on-profile:
        - dev

server:
  baseUrl: http://localhost:8080
  api:
    baseUrl: http://localhost:8080/api/v1

file-store:
  dir: "C:/Small-Community/upload"

logging:
  config: classpath:log4j2-spring-dev.xml