spring:
  config:
    activate:
      on-profile:
        - dev

server:
  port: 8443
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: temp-ssl
  baseUrl: http://localhost:8080
  api:
    baseUrl: http://localhost:8080/api/v1

file-store:
  dir: "C:/Small-Community/upload"

logging:
  config: classpath:log4j2-spring-dev.xml