spring:
  profiles:
    group:
      dev:
        - dev-env
        # 원활한 개발을 위함이며 차후 분리
        - prod-email
        - prod-oauth2
      prod:
        - prod-env
        - prod-email
        - prod-oauth2
    active: dev
  messages:
    basename: messages,errors
  servlet:
    multipart:
      max-file-size: 3MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: com.practice.smallcommunity.infrastructure.CustomMySQLDialect
  data:
    web:
      pageable:
        max-page-size: 50

management:
  server:
    port: 7070
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: /smc-mgmt
      exposure:
        include:
          - info
          - health
  endpoint:
    info.enabled: true
    health.enabled: true

cloud:
  aws:
    region:
      static: ap-northeast-2

jwt:
  access-token:
    expirationMinutes: 30
  refresh-token:
    expirationHours: 336

verification:
  email:
    api: /api/v1/members/verify
    timeoutSecond: 300
  oauth2:
    expirationMinutes: 10