spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    url: jdbc:mysql://localhost:13306/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: com.practice.smallcommunity.infrastructure.CustomMySQLDialect
    hibernate:
      ddl-auto: 'create-drop'
  data:
    web:
      pageable:
        max-page-size: 50
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      platform: dev

decorator:
  datasource:
    p6spy:
      enable-logging: true