spring:
  config:
    activate:
      on-profile:
        - dev

jwt:
  secret-key: 'DUMMY'
  access-token:
    expirationMinutes: 30
  refresh-token:
    # 14일
    expirationHours: 336

verification:
  email:
    api: /api/v1/members/verify
    # 10분
    timeoutSecond: 300
  oauth2:
    expirationMinutes: 10