spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: 'update'
  data:
    web:
      pageable:
        max-page-size: 50
  h2:
    console:
      enabled: true
      path: /h2-console

decorator:
  datasource:
    p6spy:
      enable-logging: true